"""Internal helpers shared across V/F analysis modules."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class ResidualDiagnostics:
    """Residual statistics for a fitted model.

    Attributes:
        r2: Coefficient of determination.
        residual_std: Sample standard deviation of residuals.
        residual_var: Sample variance of residuals.
    """

    r2: float
    residual_std: float
    residual_var: float


def subset_core(df: pd.DataFrame, core: int | None) -> pd.DataFrame:
    """Return either the full frame or a single-core subset.

    Args:
        df: Telemetry dataframe that may contain multiple cores.
        core: Core identifier to select. When ``None``, no filtering is applied.

    Returns:
        A dataframe containing either all rows or only rows for ``core``.

    Assumptions:
        ``df`` contains a ``core`` column when ``core`` is not ``None``.
    """

    return df if core is None else df[df["core"] == core]


def sorted_core_ids(
    df: pd.DataFrame,
    cores: Sequence[int] | None = None,
) -> list[int]:
    """Return sorted core identifiers.

    Args:
        df: Telemetry dataframe containing a ``core`` column.
        cores: Optional explicit core list. When provided, the dataframe is not
            inspected.

    Returns:
        Sorted integer core identifiers.

    Assumptions:
        Any explicit ``cores`` values are valid integers. When ``cores`` is
        omitted, the dataframe contains a ``core`` column with numeric values.
    """

    if cores is not None:
        return sorted(int(core) for core in cores)
    return sorted(int(core) for core in df["core"].dropna().unique())


def interval_midpoint(interval: pd.Interval) -> float:
    """Convert a pandas interval to its midpoint.

    Args:
        interval: Interval generated by ``pd.cut`` or ``pd.qcut``.

    Returns:
        The interval midpoint as a float.

    Assumptions:
        ``interval`` is a finite numeric interval.
    """

    return float(interval.mid)


def add_interval_midpoint(
    df: pd.DataFrame,
    *,
    interval_col: str,
    midpoint_col: str,
) -> pd.DataFrame:
    """Add a midpoint column derived from a pandas interval column.

    Args:
        df: Input dataframe containing an interval column.
        interval_col: Name of the interval column.
        midpoint_col: Name of the float midpoint column to create.

    Returns:
        A copy of ``df`` with an added midpoint column.

    Assumptions:
        ``interval_col`` contains ``pd.Interval`` objects or null values.
    """

    out = df.copy()
    out[midpoint_col] = out[interval_col].apply(interval_midpoint).astype(float)
    return out


def grouped_quantile_curve(
    df: pd.DataFrame,
    *,
    bin_column: str,
    value_column: str,
    bins: int,
    quantile: float,
    bin_label: str,
    value_label: str,
    midpoint_label: str,
    group_columns: Sequence[str] = (),
) -> pd.DataFrame:
    """Compute a quantile curve over equal-width bins.

    Args:
        df: Input dataframe.
        bin_column: Numeric column used to build equal-width bins.
        value_column: Numeric column summarized within each bin.
        bins: Number of bins for ``pd.cut``.
        quantile: Quantile of ``value_column`` to extract in each bin.
        bin_label: Output column name for the interval bins.
        value_label: Output column name for the quantile values.
        midpoint_label: Output column name for interval midpoints.
        group_columns: Optional grouping columns applied before aggregation.

    Returns:
        A dataframe containing the grouped quantile curve and midpoint column.

    Assumptions:
        ``bin_column`` and ``value_column`` are numeric and contain enough
        non-null values for the requested binning strategy.
    """

    frame = df.copy()
    frame[bin_label] = pd.cut(frame[bin_column], bins=bins)

    group_keys = [*group_columns, bin_label]
    curve = (
        frame.groupby(group_keys, observed=False)[value_column]
        .quantile(quantile)
        .reset_index(name=value_label)
    )

    curve = add_interval_midpoint(
        curve,
        interval_col=bin_label,
        midpoint_col=midpoint_label,
    )
    return curve


def residual_diagnostics(
    observed: pd.Series | np.ndarray,
    predicted: np.ndarray,
) -> ResidualDiagnostics:
    """Compute common residual diagnostics for fitted models.

    Args:
        observed: Observed target values.
        predicted: Model predictions aligned to ``observed``.

    Returns:
        Residual diagnostics containing ``r2``, residual standard deviation,
        and residual variance.

    Assumptions:
        ``observed`` and ``predicted`` are numeric, aligned, and have at least
        two rows when sample variance statistics are required.
    """

    observed_array = (
        observed.to_numpy(dtype=float)
        if isinstance(observed, pd.Series)
        else observed.astype(float)
    )
    predicted_array = predicted.astype(float)
    residuals = observed_array - predicted_array
    ss_res = float(np.sum(residuals**2))
    ss_tot = float(np.sum((observed_array - float(np.mean(observed_array))) ** 2))
    r2 = float("nan") if ss_tot == 0 else 1 - (ss_res / ss_tot)
    return ResidualDiagnostics(
        r2=r2,
        residual_std=float(np.std(residuals, ddof=1)),
        residual_var=float(np.var(residuals, ddof=1)),
    )
